CREATE TABLE IF NOT EXISTS metadata (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  sort_name TEXT,
  platform TEXT,
  genres TEXT,
  developers TEXT,
  publishers TEXT,
  categories TEXT,
  features TEXT,
  tags TEXT,
  description TEXT,
  release_date TEXT,
  series TEXT,
  pegi TEXT,
  region TEXT,
  source TEXT,
  press_rating INTEGER,
  community_rating INTEGER
);