CREATE TABLE IF NOT EXISTS game_metadata (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  sort_name TEXT,
  platform TEXT,
  genres TEXT,
  developers TEXT,
  publishers TEXT,
  categories TEXT,
  features TEXT,
  tags TEXT,
  description TEXT,
  release_date TEXT,
  series TEXT,
  pegi TEXT,
  region TEXT,
  source TEXT,
  progression TEXT,
  my_rating INTEGER,
  press_rating INTEGER,
  community_rating INTEGER,
  icon TEXT,
  logo TEXT,
  cover TEXT,
  background TEXT
);